## Introduction to Numpy

[Numpy  Package URL](https://www.numpy.org/)

In [1]:
import numpy as np

np.__version__

'1.16.2'

In [2]:
# one dimensional array
A = np.array([1,2,3,4,5,6])

print('Shape:' , A.shape)
A

Shape: (6,)


array([1, 2, 3, 4, 5, 6])

In [3]:
# two dimensional array
A = np.array([[1, 2, 3], 
              [4, 5, 6]])
# [[1 2 3]
# [4 5 6]]

print(15 * '-')
print('Shape:' , A.shape)

---------------
Shape: (2, 3)


In [4]:
# We can define the type of the inputs
Af = np.array([1, 2, 3], float)
print(Af)

print(20 * '-')
print('Shape:' , Af.shape)
# n-dimensional array
print('Type: ', type(Af))

[1. 2. 3.]
--------------------
Shape: (3,)
Type:  <class 'numpy.ndarray'>


In [5]:
# same as python's range() function but can step with decimal steps.
A = np.arange(0, 1, 0.2)
print(A)

[0.  0.2 0.4 0.6 0.8]


In [6]:
# Returns evenly spaced numbers over a specified interval.
A = np.linspace(0, 2*np.pi, 4)
A

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [7]:
A = np.linspace(0, 10, 11)
print(A)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
# Create random numpy array of shape (5,3)
A = np.random.random((5,3))
print(A)

[[0.97155402 0.00251794 0.52749002]
 [0.84381631 0.90805612 0.45090075]
 [0.51139596 0.78150565 0.23331658]
 [0.96793581 0.18992466 0.88199579]
 [0.98697518 0.39145938 0.61350173]]


In [9]:
# Create an array of shape (5,2) by sampling from a Normal distribution 
# of location (center) 0.0 and scale=2.0
a = np.random.normal(loc=0.0,
                     scale=2.0,
                     size=(5,2))
print(a)

[[ 0.33185317  1.33334683]
 [-1.9716702   1.29816099]
 [-3.01137847 -1.0624715 ]
 [-0.28547386 -3.77979271]
 [-2.87242108 -1.45688769]]


In [10]:
# Create an array of shape (5, 3) by sampling from a Normal distribution of location=0.0 and scale=1.0
a = np.random.normal(loc=0.0,
                     scale=1.0,
                     size=(5,3))
print(a)

[[-1.00627625  0.01611422 -1.27958915]
 [ 2.093143   -0.72575604  0.91178314]
 [ 1.12854796  0.35078976 -0.87010563]
 [ 0.36337001  0.26484708 -0.47122556]
 [ 1.0995113  -0.00790629 -0.71979182]]


In [11]:
# Saving a numpy array as a txt file
np.savetxt("a_out.txt", a)

In [12]:
# Saving a numpy array as a .csv file
a.tofile('foo.csv',
         sep=',',
         format='%10.5f')

In [13]:
# Second way to save an array as a .csv file.
np.savetxt("foo.csv", a, delimiter=",")

In [14]:
b = np.loadtxt("a_out.txt")
print(b, end='\n\n')
print(type(b))

[[-1.00627625  0.01611422 -1.27958915]
 [ 2.093143   -0.72575604  0.91178314]
 [ 1.12854796  0.35078976 -0.87010563]
 [ 0.36337001  0.26484708 -0.47122556]
 [ 1.0995113  -0.00790629 -0.71979182]]

<class 'numpy.ndarray'>


In [15]:
b = np.loadtxt("foo.csv", delimiter=',')
print(b)
print(type(b))

[[-1.00627625  0.01611422 -1.27958915]
 [ 2.093143   -0.72575604  0.91178314]
 [ 1.12854796  0.35078976 -0.87010563]
 [ 0.36337001  0.26484708 -0.47122556]
 [ 1.0995113  -0.00790629 -0.71979182]]
<class 'numpy.ndarray'>


In [16]:
A = np.eye(4, k=0, dtype=float)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
A = np.eye(4, k=1, dtype=float)
print(A)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [18]:
A = np.eye(4, k=-1, dtype=float)
print(A)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [19]:
A = np.zeros([4,4])
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
A = np.ones([4,4])
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
A = np.diag(range(4))
print(A)

[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [22]:
A = np.empty((4, 4))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
u = [1, 2, 3, 1]

v = [1, 1, 1, 2]

# unique elements of an array (as an array)
print('Unique elements of the arays')
print(np.unique(u))
print(np.unique(v))

Unique elements of the arays
[1 2 3]
[1 2]


In [24]:
# inner product of 2 arrays

print('Inner product of 2 arrays')
print(np.inner(u, v), end='\n\n')

Inner product of 2 arrays
8



In [25]:
# outer product of 2 arrays
# https://en.wikipedia.org/wiki/Outer_product
print('Outer product of 2 arrays')
print(np.outer(u, v), end='\n\n')

Outer product of 2 arrays
[[1 1 1 2]
 [2 2 2 4]
 [3 3 3 6]
 [1 1 1 2]]



In [26]:
# Dot Product of 2 arrays
print('Dot product of 2 arrays')
print(np.dot(u, v), end='\n\n')

Dot product of 2 arrays
8



In [27]:
# see https://www.tutorialspoint.com/numpy/numpy_tutorial.pdf

In [28]:
# Numpy's basic operations

a = np.array([1, 2, 3], float)
b = np.array([5, 2, 6], float)
print(a)
print(b)

[1. 2. 3.]
[5. 2. 6.]


In [29]:
print('Sum')
print(a + b)  # sum

Sum
[6. 4. 9.]


In [30]:
print('Subtraction')
print(a - b) # element wise subtraction 

Subtraction
[-4.  0. -3.]


In [31]:
print('Multiplication')
print(a * b) # element wise multiplication

Multiplication
[ 5.  4. 18.]


In [32]:
print('Division')
print(b / a) # element wise division

Division
[5. 1. 2.]


In [33]:
print('Modulo')
print(a % b) # element wise modulo 

Modulo
[1. 0. 3.]


In [34]:
print('Power')
print(b ** a)

Power
[  5.   4. 216.]


In [35]:
a = np.array([1.1, 2.7, 3.5], float)
a

array([1.1, 2.7, 3.5])

In [36]:
# floor for each number
print(np.floor(a))

[1. 2. 3.]


In [37]:
# ceiling for each number
print(np.ceil(a))

[2. 3. 4.]


In [38]:
# Round elements of the array to the nearest integer.
print(np.rint(a))

[1. 3. 4.]


In [39]:
# sum of all elements of the array. Same as: np.sum(a)
print(a.sum())

7.300000000000001


In [40]:
# Return the product of array elements over a given axis. Same as: np.prod(a)
print(a.prod())

10.395000000000003


In [41]:
# Average of all elements of the array. Same as: np.mean(a)
print(a.mean())

2.4333333333333336


In [42]:
# Variance of all elements of the array. Same as: np.var(a)
print(a.var())

0.9955555555555554


In [43]:
# Standard Deviation of all elements of the array. Same as: np.std(a)
print(a.std())

0.9977753031397176


In [44]:
# Min element of all elements of the array. Same as: np.min(a)
print(a.min())

1.1


In [45]:
# Max element of all elements of the array. Same as: np.max(a)
print(a.max())

3.5


In [46]:
# Given an interval, values outside the interval are clipped to the interval edges
print(a.clip(2.5, 3)) # for more info, check here: https://www.geeksforgeeks.org/numpy-clip-in-python/

[2.5 2.7 3. ]


In [47]:
a = np.array([[1,2, 3],
              [3,-1, 3],
              [3,-4, 11]], float)

b = np.array([[2, 4, 4], 
              [1, 3, 3],
              [3,-2, 2]], float)

In [48]:
print('Two numpy arrays: ', end='\n\n')
print(a)

print()

print(b)

Two numpy arrays: 

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]]

[[ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]


In [49]:
print('Element wise Multiplication')
print(a * b)

Element wise Multiplication
[[ 2.  8. 12.]
 [ 3. -3.  9.]
 [ 9.  8. 22.]]


In [50]:
print('Slicing Array A')
print(a[1:2, :])  # 1:2 slices the rows. The ":" means "give me every value"

Slicing Array A
[[ 3. -1.  3.]]


In [51]:
print('Dot Product of two nd-arrays:')
print(np.dot(a, b))

Dot Product of two nd-arrays:
[[ 13.   4.  16.]
 [ 14.   3.  15.]
 [ 35. -22.  22.]]


In [52]:
print('Maximum values of the dot product of the 2 nd-arrays for each column (for all rows)')
print(np.max(np.dot(a, b) , 0))

Maximum values of the dot product of the 2 nd-arrays for each column (for all rows)
[35.  4. 22.]


In [53]:
print('Maximum values of the dot product of the 2 nd-arrays for each row (for all columns)')
print(np.max(np.dot(a, b) , 1))

Maximum values of the dot product of the 2 nd-arrays for each row (for all columns)
[16. 15. 35.]


In [54]:
print('Maximum values of the dot product of the 2 nd-arrays in respect to the last dimension')
print(np.max(np.dot(a, b) , -1))

Maximum values of the dot product of the 2 nd-arrays in respect to the last dimension
[16. 15. 35.]


In [55]:
a = np.array([[1, 2, 3],
              [3,-1, 3],
              [3,-4, 11]], float)

b = np.array([[2, 4, 4], 
              [1, 3, 3],
              [3,-2, 2]], float)

# Stacking arrays (concatenating)

# Vertical stacking
stacked_v = np.vstack([a,b])

# Horizontal stacking
stacked_h = np.hstack([a,b])

In [56]:
print(stacked_v, end='\n\n')
print(stacked_v.shape)

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]
 [ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]

(6, 3)


In [57]:
print(stacked_h, end='\n\n')
print(stacked_h.shape)

[[ 1.  2.  3.  2.  4.  4.]
 [ 3. -1.  3.  1.  3.  3.]
 [ 3. -4. 11.  3. -2.  2.]]

(3, 6)


In [58]:
# Reshaping arrays (the product of the dimensions must always match (before and after reshaping))
a = stacked_v.reshape(2, 9)

print(stacked_v, end='\n\n')

print(a, end='\n\n')

print(a.shape)

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]
 [ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]

[[ 1.  2.  3.  3. -1.  3.  3. -4. 11.]
 [ 2.  4.  4.  1.  3.  3.  3. -2.  2.]]

(2, 9)


In [59]:
b = stacked_v.reshape(1, 18)

print(stacked_v, end='\n\n')

print(b, end='\n\n')
print(b.shape)

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]
 [ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]

[[ 1.  2.  3.  3. -1.  3.  3. -4. 11.  2.  4.  4.  1.  3.  3.  3. -2.  2.]]

(1, 18)


In [60]:
c = stacked_v.reshape(18, 1)

print(stacked_v, end='\n\n')

print(c, end='\n\n')

print(c.shape)

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]
 [ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]

[[ 1.]
 [ 2.]
 [ 3.]
 [ 3.]
 [-1.]
 [ 3.]
 [ 3.]
 [-4.]
 [11.]
 [ 2.]
 [ 4.]
 [ 4.]
 [ 1.]
 [ 3.]
 [ 3.]
 [ 3.]
 [-2.]
 [ 2.]]

(18, 1)


In [61]:
d = stacked_v.reshape(1, -1)

print(stacked_v, end='\n\n')

print(d, end='\n\n')
print(d.shape)

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]
 [ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]

[[ 1.  2.  3.  3. -1.  3.  3. -4. 11.  2.  4.  4.  1.  3.  3.  3. -2.  2.]]

(1, 18)


In [62]:
e = stacked_v.reshape(-1, 1)

print(e, end='\n\n')
print(e.shape)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 3.]
 [-1.]
 [ 3.]
 [ 3.]
 [-4.]
 [11.]
 [ 2.]
 [ 4.]
 [ 4.]
 [ 1.]
 [ 3.]
 [ 3.]
 [ 3.]
 [-2.]
 [ 2.]]

(18, 1)


In [63]:
flat_array = np.ndarray.flatten(stacked_v)

flat_array

array([ 1.,  2.,  3.,  3., -1.,  3.,  3., -4., 11.,  2.,  4.,  4.,  1.,
        3.,  3.,  3., -2.,  2.])

In [64]:
# check the difference in shape
flat_array.shape

(18,)

In [65]:
# More about reshaping in this thread:
# https://stackoverflow.com/questions/22053050/difference-between-numpy-array-shape-r-1-and-r