# Big Data Content Analytics - AUEB

## Introduction to Feed Forward Networks for Image

* Lab Assistant: George Perakis
* Email: gperakis[at]aeub.gr 

In [1]:
# imports

from tensorflow.keras.datasets import mnist
from ipywidgets import interact
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
# train_images and train_labels form the training set, the data that the model will
# learn from. 
# The model will then be tested on the test set, test_images and test_labels .
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [9]:
@interact
def show_image(index=100):
    digit = train_images[index]
    plt.imshow(digit, cmap=plt.cm.binary)

interactive(children=(IntSlider(value=100, description='index', max=300, min=-100), Output()), _dom_classes=('…

In [10]:
# model imports

from tensorflow.keras import models
from tensorflow.keras import layers

In [11]:
network = models.Sequential()

network.add(layers.Dense(512,
                         activation='relu',
                         input_shape=(28 * 28,)))

network.add(layers.Dense(10,
                         activation='softmax'))

In [12]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [13]:
train_images = train_images.reshape((60000, 28 * 28))

train_images = train_images.astype('float32') / 255

In [14]:
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [15]:
train_images.shape

(60000, 784)

In [16]:
test_images.shape

(10000, 784)

In [17]:
# We also need to categorically encode the labels
from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [18]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [19]:
train_labels.shape

(60000, 10)

In [20]:
# We’re now ready to train the network
network.fit(train_images, 
            train_labels,
            epochs=10,
            batch_size=128,
            validation_split=0.1)

Epoch 1/10
422/422 [==============================] - 4s 7ms/step - loss: 0.4505 - accuracy: 0.8677 - val_loss: 0.1311 - val_accuracy: 0.9613
Epoch 2/10
422/422 [==============================] - 2s 4ms/step - loss: 0.1228 - accuracy: 0.9638 - val_loss: 0.0867 - val_accuracy: 0.9750
Epoch 3/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0738 - accuracy: 0.9789 - val_loss: 0.0758 - val_accuracy: 0.9780
Epoch 4/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0512 - accuracy: 0.9847 - val_loss: 0.0715 - val_accuracy: 0.9790
Epoch 5/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0374 - accuracy: 0.9889 - val_loss: 0.0676 - val_accuracy: 0.9803
Epoch 6/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0280 - accuracy: 0.9923 - val_loss: 0.0681 - val_accuracy: 0.9818
Epoch 7/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0197 - accuracy: 0.9948 - val_loss: 0.0736 - val_accuracy: 0.9818
Epoch 

In [21]:
# Evaluation
test_loss, test_acc = network.evaluate(test_images, 
                                       test_labels)

313/313 [==============================] - 1s 3ms/step - loss: 0.0701 - accuracy: 0.9831


In [22]:
print('test_acc:', test_acc)

test_acc: 0.9830999970436096
